#ifndef COMM_INTERN_H
#define COMM_INTERN_H

#define MARQUEUR 0xFE

#define SEQ_DECOLLAGE 0xF1
#define SEQ_PARACHUTE 0xF2
#define SEQ_ACQUITTEMENT_DECOLLAGE 0xE2
#define SEQ_ACQUITTEMENT_APOGEE 0xE3

#define EXP_DECOLLAGE 0xF3
#define EXP_APOGEE 0xF4
#define EXP_ACQUITTEMENT 0xE1


#endif